version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379"

  prerender:
    image: witchman/prerender-with-redis
    ports:
      - "1338:3000"
    environment:
      - REDIS_URL=redis://redis/10
    links:
      - redis
